# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app. You can rename and customize it as you want.
  build-and-test:
    working_directory: ~/Netflix-Pathways-Bootcamp-Final-Project/gamestore

    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Docker Hub or use one of our Convenience assets from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to the openjdk version of your application.
    # A list of available CircleCI Docker Convenience assets are available here: https://circleci.com/developer/assets/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:8.0
      # Add steps to the job
      # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Check out the code as the first step.
      - checkout:
          path: ~/Netflix-Pathways-Bootcamp-Final-Project
      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow. Feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test